# Generated by Django 4.2.7 on 2023-11-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.FileField(default='image.jpg', upload_to='documents'),
        ),
    ]
