# Generated by Django 4.2.7 on 2023-11-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directx', '0002_students_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_weight', models.IntegerField()),
                ('pro_price', models.CharField(max_length=30)),
                ('pro_image', models.FileField(default='image.jpg', upload_to='documents')),
            ],
        ),
    ]
